Created the landing page and the pop-up menu
rolandfbk/portfolio pull request #1
Opened 2022-03-16 19:45 UTC by rolandfbk

The landing page and the pop-up menu have been created by replicating the design of template 5 of the Microverse-Student-Project-1 on figma.com. As required, I tried to stick to the design as much as possible.

2022-03-16 20:38 UTC, Donard97 requested changes
## Hello @rolandfbk , 👋  

You did a tremendous job so far! 💯 👏 

There are some issues that you still need to work on to go to the next project but you are almost there! 💪 

![133678845-1b015b27-e9bc-4784-a316-bc699db8237a](https://user-images.githubusercontent.com/74506933/158686467-4d8c0924-f36a-4527-8657-0b2e361a33c1.jpg)

## Highlights 🏁 

- There is no linter error ✅ 
- Code is clean ✅ 
- Readme file is professional ✅ 

## Required Changes ♻️
- [ ] Kindly add the .hintrc file for linters following linters configuration [repository](https://github.com/microverseinc/linters-config/tree/master/html-css)
- [ ] I suggest you in the future to do more commits because it is a really good habit and it is professional.
- [ ] Please check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-16 20:38 UTC, Donard97 commented on index.html
> +                <div class="content set">
- [ ] Well done on adding the first section of the portfolio but kindle stick as much as you can to [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9). Keep rocking 💪 

Here you have a screenshot from your project:

![image](https://user-images.githubusercontent.com/74506933/158685072-b556925f-93f5-4531-b66c-6cc0ffb7091a.png)

Here you have a screenshot from the design:

![image](https://user-images.githubusercontent.com/74506933/158685142-51ae9bd4-643f-4ae3-a833-4f7f043a4cd7.png)

2022-03-16 20:38 UTC, Donard97 commented on index.html
> +                    <img class="f-img" src="img/image_geometry_2.svg" alt="">
- [ ] Good job on adding the button and styling it but kindly stick as much as you can to  [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9).

Here you have a screenshot from your project:

![image](https://user-images.githubusercontent.com/74506933/158685390-0eb42cbf-48bc-4215-9130-5f615c20b58a.png)

Here you have a screenshot from the design:

![image](https://user-images.githubusercontent.com/74506933/158685423-8c7b9104-e2fb-4383-b600-fba6eb487311.png)

2022-03-16 20:38 UTC, Donard97 commented on index.html
> +                    <img class="f-img" src="img/image_geometry_menu_2.svg" alt="">
- [ ] Well done on adding the image but this is a background image so kindly change it to the background and not the img tag. Keep coding 💪

2022-03-16 20:38 UTC, Donard97 commented on index.html
> +                    <img src="img/image_geometry_1.svg" alt="">
- [ ] Well done on adding the image but this is a background image so kindly change it to the background and not the img tag. Keep coding 💪

2022-03-17 09:05 UTC, aimemalaika approved these changes
Hi @rolandfbk , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 13:23 UTC, merged